// Tiny inline previews so photographs fade in rather than pop.
// Generated from the 2560px WebP sources; keys are the path under
// /public/images without the extension, so names cannot collide
// between folders. Regenerate with sharp if a source photo changes.
export const BLUR: Record<string, string> = {
  'amenities/fridges': 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoMABIAPzmEuVOvKKWisAgB4CcJQBfnBEQSRD99qCjASwAA/rQFarntvQUoyQvZT4FGREaJLCeAy1ctJQ2LKlKP9M52zQMVzVQ5dLFx5/Js3zU1idAAAA==',
  'amenities/kitchen-counter': 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAgABUB8JQBOgBcOGXUYAP4+O8qFRY446py4cOhX1rrQmknXtykQ6wilM2BmEAA=',
  'amenities/kitchen-members': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAgABUB8JYgCdADcEl/GAAD+LlMNVJ9Nz1z4WgWt3Y7CiNymSaYTP4WyXesg6+cAAA==',
  'amenities/kitchen': 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMABAABUB8JQAAMtdyDY5ZAADcxq5D9AtUAAixUERmHjmtkJpHfO9m/A6XC8INjZLMsqZi/Hn1wfHfvp2oAA==',
  'amenities/lockers': 'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoMABIAPzmGulOvKSWisAgB4CcJYwCdABofjZqHMO7MAAD+gONMqMs4HazR5prn702qMI36gil330j46y7KL4/EAAA=',
  'amenities/snackshop-case': 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoMABIAPzmEuVOvKKWisAgB4CcJYgCdMoACpiZ7ZTdHLcAA9gj11I256VAW+t7bLrFTAvI2m6ebqFRd3GDM6sAMvYVT+8roFDlhGhUlljIRuK31greI04zwatZ4AAAA',
  'conference-room/empty': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAgABUB8JYgCdADaQD1dgAD+TMGLEq7bMcaIMchz8Wg1ZjaVAB2OK+glz5P8iHEAAA==',
  'conference-room/meeting': 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoMAAgABUB8JbAC7AEDpUCW9fQAAP5fbY668/7Pz/1DVXLMEgb9hYLqyozxH83Yk5D4O+r6gbwAAA==',
  'conference-room/wide': 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoMABAABUB8JbACsAEesBQVEd+wAPyL2FFkA/fZckNilJc5O9Pt5zh8crVqERoUw+rrFyl1bvwBBPWLUfmD36ynxQGAAA==',
  'dedicated-desks/members-talking': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAgABUB8JYgCdADg2c0AAMyK9Vw1VrTsqBF8F4FWxJlDf6zjPbfN60zC9GhGW6nfo8US9fj8wAAA',
  'dedicated-desks/pods-alt-angle': 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAgABUB8JYgCdADZochLYAD9LBSnngzpPmB5YxAu4xK8Nk1Zk2a5+4bu/vf2vDHvYcMAAAA=',
  'dedicated-desks/room-empty-alt': 'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMABAABUB8JbACdADZlr0bPnAA+FsussrNz68GwywSGJCphIi2doy0NwM0Vnnmv0VPP7G+dEoN+gTfQH0WeHOrgAA=',
  'dedicated-desks/room-empty': 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoMABAABUB8JbACdADdlE17VAU6AADiO51P5Gk+aaTbf9F1fmxtOfw1pjEBC7mqcJuIPZa2/8O/aT/e+FpEpIAA',
  'dedicated-desks/room-occupied': 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoMAAgABUB8JQBOgCLZ0WLhVYAA/hnYNt71E3gujbhU44D0rDisYv8401yNlqU+AAA=',
  'dedicated-desks/room-wide-alt-1': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoMAAgABUB8JQBOgCLZzKpQ0AAA/hnYNt71E3gujbhU44D0rDjj0SQHqANXNqGumwKAAA==',
  'dedicated-desks/room-wide-alt-2': 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAAgABUB8JZgCdAEem4HdW1gA4iqnpnoTa7IEcYle45yQcVrunxzd/vSwveYsr4ldMlkAAAA=',
  'dedicated-desks/room-wide': 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoMAAgABUB8JZACdAEem4Hd59cAAOIqp6Z6E2uyBHGKGS1FqYgvYtPy+lw4vtuGSxlZ6dISAAA=',
  'dedicated-desks/two-members': 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAAgABUB8JZACdADdc8t5FXLgAPpOJvAwI4mCL6DQQTtLerEvMoM8SZd1NRkdbLqCqsCo6a3H62763CAAAA==',
  'exterior/campus-corner': 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAgABUB8JYgCdADb67SoQAD+q9H0+VYGjsRkQVqX/HPcGf/5Nul2kJbyEZI7qyncAAAA',
  'exterior/campus': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAYABUB8JZgC7ADcSQtFiwAA/hnGQCtIBU0DJocZG/tXvGNxsRQjUXqVMgAA',
  'exterior/signage': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAgABUB8JQBOgB6OPANQAAD+qU5GYxQaznoTXd5ZtwTzYpJV7YMeZHAqjC58QgAAAA==',
  'exterior/street-flags': 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoMABIAPzmEuVOvKKWisAgB4CcJYgC7ABsvF4+SCIuKFwAA/iRWA1npfrMOOLsxsU7eQ+ZijDYv9Ww19cJ8262J9nEc8iT78j78lqaesb1wQJmt2VWChOJMi89pOD4hAAA=',
  'flex-space/cafe': 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAkABUB8JYwAAjq4CIVwAPndV0F5tIdglQMS8wbkkeqg8bi9xgcAAAA=',
  'flex-space/exterior': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAkABUB8JagCdAD8LQGiIgAA/qDrRwetLrFf/QcExbITE7mg0BbaN1IS/qWEpC7x+KDQdKybUQAA',
  'flex-space/hall-1': 'data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAADQAQCdASoMAAkABUB8JQBOgCIBazZYAAD9QbQ/FvkOh9a7vIsAAA==',
  'flex-space/hall-2': 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAAkABUB8JQBOgBZk0484AP1FLoS4qPNm2iqqnOt+SxrHy+0HAAAA',
  'flex-space/rose-window-group': 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAgABUB8JbACdAEWBW2qMAAA/rWtiESxn0t4G/Bnf5rILAup7xNtKeEk1Q5VZQGr5ZQDTwAAAA==',
  'offices/four-desk-alt': 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAQCdASoMABAABUB8JYwAAZWH6AAA9b7mdaXGOyl0s4xFgE789gWwc/nD4kF3LJN5W6GIaAA=',
  'offices/four-desk': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMABAABUB8JYgC7AEezuJXAADw3BlcEI6P5eKikPWYVEukjeZA925lhcItAAAA',
  'offices/large-occupied': 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoMAAgABUB8JZACdACNjGAA9rwmVjQDH/5c1ON9JQL9H8FKeuI9bNwH5GAkVNzj8yFXLmXMrAqwAA==',
  'offices/large-team': 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgABUB8JbACdAELKYN83AD4x5/79YnevX3Y2hW53ThZqiBASL36EmvhnZ4Jt77WRDGR9bkbE11FTxQAAA==',
  'offices/phone-booth': 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoMABAABUB8JZQC7ABzMSgA4M7eWLlyQdUvd/CJT/gahVq46AAAAA==',
  'offices/single-alt-2': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACQAQCdASoMABAABUB8JYwAAQawvAAAynzr6AjoU7pNwpAICPM/2twFxebxNCA9r35YAAAA',
  'offices/single-alt': 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoMABAABUB8JZQC7ABZZkAAzY5rX4OB7EYdH0fnwzYSQk9jd8vwXi4aWMAAAA==',
  'offices/single-daylight': 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAgABUB8JZQCdADcTXpxAAD6QwabcsZYqS9t2f74ZCtyVVKyWWR//A7QI5BcGAA=',
  'offices/single-occupied': 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAAgABUB8JZQCo9EK1AORGoAA/gH6Zbn1YlrJ/JXaOJd8Ge5t38fvup1U7tz1iy3tZqcAAAA=',
  'offices/two-desk-alt': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoMABAABUB8JZQAAv4cwDcwAOearfImXkd9MivIPfH3clMyh1WSRyXNLuAZsvAA',
  'offices/two-desk': 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoMABAABUB8JQBdgBDti/AA7/ewcl2AZ1XsVbRZnqtR2WT1b0BFNYuIAAA=',
};
